language: c
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq build-essential pike7.8
- sudo apt-get build-dep -qq pike7.8
sudo: false
cache: ccache
env:
  global:
      - USE_CCACHE=1
      - CCACHE_COMPRESS=1
script: echo $PATH; ccache -s; (cd src && ./run_autoconfig .) && make && make verify
